insert into CodPostal (CodPostal, Localidade) values (1, 'Połaniec');
insert into CodPostal (CodPostal, Localidade) values (2, 'Tonoshō');
insert into CodPostal (CodPostal, Localidade) values (3, 'Changtan');
insert into CodPostal (CodPostal, Localidade) values (4, 'Smolenka');
insert into CodPostal (CodPostal, Localidade) values (5, 'Shuiyang');
insert into CodPostal (CodPostal, Localidade) values (6, 'Thiais');
insert into CodPostal (CodPostal, Localidade) values (7, 'Guadalupe');
insert into CodPostal (CodPostal, Localidade) values (8, 'Samur');
insert into CodPostal (CodPostal, Localidade) values (9, 'Purral');
insert into CodPostal (CodPostal, Localidade) values (10, 'Jati');
insert into CodPostal (CodPostal, Localidade) values (11, 'La Cumbre');
insert into CodPostal (CodPostal, Localidade) values (12, 'Krasnoznamensk');
insert into CodPostal (CodPostal, Localidade) values (13, 'Digah');
insert into CodPostal (CodPostal, Localidade) values (14, 'Būrewāla');
insert into CodPostal (CodPostal, Localidade) values (15, 'Boissy-Saint-Léger');
insert into CodPostal (CodPostal, Localidade) values (16, 'Guadalupe');
insert into CodPostal (CodPostal, Localidade) values (17, 'El Jícaro');
insert into CodPostal (CodPostal, Localidade) values (18, 'Prozor');
insert into CodPostal (CodPostal, Localidade) values (19, 'Penha');
insert into CodPostal (CodPostal, Localidade) values (20, 'Podstepki');
insert into CodPostal (CodPostal, Localidade) values (21, 'Gualán');
insert into CodPostal (CodPostal, Localidade) values (22, 'Pithári');
insert into CodPostal (CodPostal, Localidade) values (23, 'Aldeia');
insert into CodPostal (CodPostal, Localidade) values (24, 'Saint-Maurice');
insert into CodPostal (CodPostal, Localidade) values (25, 'Langley');
insert into CodPostal (CodPostal, Localidade) values (26, 'Hanau');
insert into CodPostal (CodPostal, Localidade) values (27, 'Quinchía');
insert into CodPostal (CodPostal, Localidade) values (28, 'Las Varillas');
insert into CodPostal (CodPostal, Localidade) values (29, 'Kleszczów');
insert into CodPostal (CodPostal, Localidade) values (30, 'Buenaventura');
insert into CodPostal (CodPostal, Localidade) values (31, 'Porto Seguro');
insert into CodPostal (CodPostal, Localidade) values (32, 'Bélel');
insert into CodPostal (CodPostal, Localidade) values (33, 'Wielbark');
insert into CodPostal (CodPostal, Localidade) values (34, 'San Onofre');
insert into CodPostal (CodPostal, Localidade) values (35, 'Vallehermoso');
insert into CodPostal (CodPostal, Localidade) values (36, 'Muara');
insert into CodPostal (CodPostal, Localidade) values (37, 'Santa Elena');
insert into CodPostal (CodPostal, Localidade) values (38, 'Eshowe');
insert into CodPostal (CodPostal, Localidade) values (39, 'Bemposta');
insert into CodPostal (CodPostal, Localidade) values (40, 'Moses');
insert into CodPostal (CodPostal, Localidade) values (41, 'Pliska');
insert into CodPostal (CodPostal, Localidade) values (42, 'Ozamiz City');
insert into CodPostal (CodPostal, Localidade) values (43, 'Tosontsengel');
insert into CodPostal (CodPostal, Localidade) values (44, 'Chengzihe');
insert into CodPostal (CodPostal, Localidade) values (45, 'Calimita');
insert into CodPostal (CodPostal, Localidade) values (46, 'Tân Trụ');
insert into CodPostal (CodPostal, Localidade) values (47, 'Lapuz');
insert into CodPostal (CodPostal, Localidade) values (48, 'Zaki Biam');
insert into CodPostal (CodPostal, Localidade) values (49, 'Xam Nua');
insert into CodPostal (CodPostal, Localidade) values (50, 'Lavandeira');
insert into CodPostal (CodPostal, Localidade) values (51, 'Kablukan');
insert into CodPostal (CodPostal, Localidade) values (52, 'Prioso Barat');
insert into CodPostal (CodPostal, Localidade) values (53, 'Ambohitrolomahitsy');
insert into CodPostal (CodPostal, Localidade) values (54, 'Sarnia');
insert into CodPostal (CodPostal, Localidade) values (55, 'Mętków');
insert into CodPostal (CodPostal, Localidade) values (56, 'Qiakeri');
insert into CodPostal (CodPostal, Localidade) values (57, 'Varkaus');
insert into CodPostal (CodPostal, Localidade) values (58, 'San Pedro Carchá');
insert into CodPostal (CodPostal, Localidade) values (59, 'Rungis');
insert into CodPostal (CodPostal, Localidade) values (60, 'Layog');
insert into CodPostal (CodPostal, Localidade) values (61, 'Mbala');
insert into CodPostal (CodPostal, Localidade) values (62, 'Molinos');
insert into CodPostal (CodPostal, Localidade) values (63, 'Guiping');
insert into CodPostal (CodPostal, Localidade) values (64, 'Muting');
insert into CodPostal (CodPostal, Localidade) values (65, 'Kalisabuk');
insert into CodPostal (CodPostal, Localidade) values (66, 'Queimados');
insert into CodPostal (CodPostal, Localidade) values (67, 'Seremban');
insert into CodPostal (CodPostal, Localidade) values (68, 'Kudang');
insert into CodPostal (CodPostal, Localidade) values (69, 'Zdíkov');
insert into CodPostal (CodPostal, Localidade) values (70, 'Kihurio');
insert into CodPostal (CodPostal, Localidade) values (71, 'Jixing');
insert into CodPostal (CodPostal, Localidade) values (72, 'Aguilares');
insert into CodPostal (CodPostal, Localidade) values (73, 'Kemijärvi');
insert into CodPostal (CodPostal, Localidade) values (74, 'Abashiri');
insert into CodPostal (CodPostal, Localidade) values (75, 'Luleå');
insert into CodPostal (CodPostal, Localidade) values (76, 'Maisí');
insert into CodPostal (CodPostal, Localidade) values (77, 'Tubungan');
insert into CodPostal (CodPostal, Localidade) values (78, 'Hila');
insert into CodPostal (CodPostal, Localidade) values (79, 'Pedra Azul');
insert into CodPostal (CodPostal, Localidade) values (80, 'Krylovskaya');
insert into CodPostal (CodPostal, Localidade) values (81, 'Tianxin');
insert into CodPostal (CodPostal, Localidade) values (82, 'Anserma');
insert into CodPostal (CodPostal, Localidade) values (83, 'Liangchahe');
insert into CodPostal (CodPostal, Localidade) values (84, 'Jardín');
insert into CodPostal (CodPostal, Localidade) values (85, 'Belén');
insert into CodPostal (CodPostal, Localidade) values (86, 'Villamontes');
insert into CodPostal (CodPostal, Localidade) values (87, 'Beraim');
insert into CodPostal (CodPostal, Localidade) values (88, 'Zhoushizhuang');
insert into CodPostal (CodPostal, Localidade) values (89, 'El Progreso');
insert into CodPostal (CodPostal, Localidade) values (90, 'Mariental');
insert into CodPostal (CodPostal, Localidade) values (91, 'Mutā Khān');
insert into CodPostal (CodPostal, Localidade) values (92, 'Bayonne');
insert into CodPostal (CodPostal, Localidade) values (93, 'Lucban');
insert into CodPostal (CodPostal, Localidade) values (94, 'Boquira');
insert into CodPostal (CodPostal, Localidade) values (95, 'Borāzjān');
insert into CodPostal (CodPostal, Localidade) values (96, 'Orlando');
insert into CodPostal (CodPostal, Localidade) values (97, 'Ponte');
insert into CodPostal (CodPostal, Localidade) values (98, 'Stutterheim');
insert into CodPostal (CodPostal, Localidade) values (99, 'Bergen');
insert into CodPostal (CodPostal, Localidade) values (100, 'Daxi');
